#!/bin/bash
# multi protocol bash script to auto opening given URI and auto creating ssh reverse tunnel socks proxy
# very useful to use with KeePassX or any Desktop/Browser Password Manager as secure URI launcher
# Written by Ugo Viti <ugo.viti@initzero.it>
#    date: 20200108
# version: 2.5

# features:
#    URI handling of: ssh, rdp, vnc, sftp, ftp, http, https, smb and cifs schemas

# installation:
#        simply copy this script into a user or system wide bin directory (suggestion: cp izopen ~/bin), must be into a PATH variable

# usage: izopen uri://username:password@address:port

# examples:
#        izopen http://www.example.com
#        izopen http://john:doe@www.example.com
#        izopen ssh://root:supersecurepassword@www.example.com
#        izopen smb://Administrator:password@server
#        izopen rdp://DOMAIN/Administrator:password@server
#        izopen rdp:///Administrator:password@server

# KeePassX 0.x integration:
#        into advanded settings of keepassx select "Custom Browser Command" and insert:
#        izopen %1
#        for every account stored into your database, write into URL field: uri://{USERNAME}:{PASSWORD}@address:port
#        example: rdp://{USERNAME}:{PASSWORD}@www.example.com:3389

# KeePassX 2.x integration (Fedora >= 23):
#        dnf install -y yad kdelibs3 proxychains-ng keepassx


# variables
#########################################################################
debug=1				# enable script debug

helper_http_chrome=1		# use google chrome as web browser (this needed because proxychains doens't works with google chrome)

tunnel_create_force=1		# always create the tunnel for every new ssh connection
tunnel_use_force=1		# always use the tunnel for every opened url
tunnel_use_force_ssh=0		# always use the tunnel if connecting via ssh

izopen_tmp_dir="$HOME/.config/izopen"
tunnel_port_min=2000
tunnel_port_max=4999
izopen_tmp_socks_port_current="$izopen_tmp_dir/socks_port_current.conf"
[ -e "$izopen_tmp_socks_port_current" ] && tunnel_port_current="$(cat "$izopen_tmp_socks_port_current")"

# import configuration from izopen.conf if exist
[ -f "/tmp/izopen.conf" ] && . /tmp/izopen.conf

# commands helper functions
#########################################################################
helper_ssh() {
  # define the command to use based on current desktop environment
  if   [ "$XDG_CURRENT_DESKTOP" = "MATE" ]; then
    helper_cmd_terminal="$(gsettings get org.mate.applications-terminal exec | tr -d \')"
  elif [ "$XDG_CURRENT_DESKTOP" = "GNOME" ]; then
    helper_cmd_terminal="$(gsettings get org.gnome.desktop.default-applications.terminal exec | tr -d \')"
  elif [ "$XDG_CURRENT_DESKTOP" = "KDE" ]; then
    #helper_cmd_terminal="$(kreadconfig --file kdeglobals --group General --key TerminalApplication | tr -d \')"
    helper_cmd_terminal="konsole"
  elif [ "$XDG_CURRENT_DESKTOP" = "XFCE" ]; then
    helper_cmd_terminal="exo-open --launch TerminalEmulator"
  elif [ "$XDG_CURRENT_DESKTOP" = "Pantheon" ]; then
    #C3d4dm1n24!helper_cmd_terminal="io.elementary.terminal"
    helper_cmd_terminal="exo-open --launch TerminalEmulator"
   else
    helper_cmd_terminal="xterm"
  fi

  [ -z "$username" ] && read -p "username: " username;
  #[ -z "$password" ] && read -p "password: " password;
  
  [ -n "$port" ] && helper_cmd_opts+="-p $port "

  helper_cmd_opts+="-C $username@$address"

  # set the final command
  helper_cmd="$helper_cmd_terminal --title \"$([ "$tunnel_create" = 1 ] && echo "H:$address P:$tunnel_port_create" || echo "H:$address")\" -e \"ssh $helper_cmd_opts\""

  ####################### 
  # test colorized prompt
  #helper_cmd="gnome-terminal -e \"ssh $([ -n "$port" ] && echo "-p $port") $username@$address $helper_cmd_opts\""
  #helper_cmd_ssh_opts="--title \"export PS1='\e[0;31m[\u@\h \W]\$ \e[m '; exec bash\""
}

helper_telnet() {
  helper_cmd_terminal="mate-terminal"
  #helper_cmd_terminal="terminator"
  #helper_cmd_terminal="gnome-terminal"
  #helper_cmd_terminal="konsole"
  #helper_cmd_terminal="xfce4-terminal"

  [ -z "$username" ] && read -p "username: " username;
  #[ -z "$password" ] && read -p "password: " password;
  
  helper_cmd_opts+=" $address$([ -n "$prt" ] && echo " $port")"

  # set the final command
  helper_cmd="$helper_cmd_terminal --title \"$([ "$tunnel_create" = 1 ] && echo "H:$address P:$tunnel_port_create" || echo "H:$address")\" -e \"telnet $helper_cmd_opts\""

  ####################### 
  # test colorized prompt
  #helper_cmd="gnome-terminal -e \"ssh $([ -n "$port" ] && echo "-p $port") $username@$address\""
  #helper_cmd_ssh_opts="--title \"export PS1='\e[0;31m[\u@\h \W]\$ \e[m '; exec bash\""
}


helper_rdp() {
  #helper_cmd_rdp="rdesktop"
  helper_cmd_rdp="xfreerdp"

  # extract windows domain from username and convert to the right name
  if [ ! -z $(echo "$username" | grep "@") ]; then
    domain="$(echo "$username" | awk -F"@" '{print $2}')"
    username="$(echo "$username" | awk -F"@" '{print $1}')"
  fi

  if [ ! -z $(echo "$username" | grep "/") ]; then
    domain="$(echo "$username" | awk -F"/" '{print $1}')"
    username="$(echo "$username" | awk -F"/" '{print $2}')"
  fi

  # FIXME
  #password="$(echo "$password" | sed -e 's/%\([A-Z]\)/%\L\1/')" # keepassxc bug workaround: after the '%' char, keepassxc convert to uppercase the following char
  password="$(echo "$password" | sed 's/\%25/\%/g' | sed -e 's/%\([A-Z]\)/%\L\1/')" # keepassxc bug workaround: after the '%' char, keepassxc convert to uppercase the following char

  # special characters in password like ' !
  password="$(echo "$password" | sed -e "s/'/\\\'/g" -e "s/!/\\\!/g")"

  #[ -z "$username" ] && username=$domain && unset domain
  #username="$(echo "$username" | sed 's/\//\\\\/g')"

  if [[ -z "$address" || -z "$username" || -z "$password" || "$username" = "{USERNAME}" || "$password" = "{PASSWORD}" || "$username" = "%7BUSERNAME%7D" || "$password" = "%7BPASSWORD%7D" ]]; then
    frmdata=$(yad --center --width=300 --title "Connect to remote computer" --focus-field=4 --align=right --form --field="Domain" "$domain" --field="Address" "$address" --field="Username" "$username" --field="Password:H" "$password" --field="Security:CB" 'rdp!tls!^nla!ext' | grep -v "WINDOW DECORATIONS RELOADED")
    [ $? != 0 ] && exit 1
    domain=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $1 }')
    address=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $2 }')
    username=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $3 }')
    password=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $4 }')
    sec=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $5 }')
  fi

  case $helper_cmd_rdp in
    rdesktop)
      helper_cmd="$helper_cmd_rdp -k it -g 1280x780 $([ -n "$domain" ] && echo "-d \"$domain\"") $([ -n "$username" ] && echo "-u \"$username\"")  $([ -n "$password" ] && echo "-p \"$password\"") $address$([ -n "$port" ] && echo ":$port")"
      ;;
    xfreerdp)
      helper_cmd_opts+="/drive:r,/ramdisk +clipboard /kbd:Italian /size:85% /cert-tofu /cert-ignore /log-level:ERROR"
      [ ! -z "$sec" ]      && helper_cmd_opts+=" /sec:$sec"
      [ ! -z "$domain" ]   && helper_cmd_opts+=" /d:\"$domain\""
      [ ! -z "$username" ] && helper_cmd_opts+=" /u:\"$username\""
      [ ! -z "$password" ] && helper_cmd_opts+=" /p:\"$password\""
      [   -z "$password" ] && helper_cmd_opts+=" /p:\"\""
      [ ! -z "$port" ]     && helper_cmd_opts+=" /port:$port"

      helper_cmd="$helper_cmd_rdp "$helper_cmd_opts" /v:$address"
      ;;
  esac
}

helper_vnc() {
  # vnc doesn't support username and actually don't accept the password. use the gnome keyring instead for this
  #helper_cmd="vinagre $schema://$address$([ -n $port ] && echo ":$port")"
  helper_cmd="vncviewer $address$([ -n $port ] && echo ":$port")"
}

helper_sftp() {
  #helper_cmd="xdg-open \"$args\""
  helper_cmd="helper_ssh \"$args\""
}

helper_ftp() {
  helper_cmd="xdg-open \"$args\""
}

helper_http() {
  if [ "$tunnel_use" = 1 ] 
    then
	if [ $helper_http_chrome = 1 ] ; then
	  #helper_cmd="google-chrome --media-cache-size=1 --disk-cache-size=1 --disable-client-side-phishing-detection --disable-gpu --restore-last-session --no-first-run --disable-translate --password-store=basic --user-data-dir=\"$izopen_tmp_dir/google-chrome-$tunnel_port_current\" --proxy-server=\"socks5://localhost:$tunnel_port_current\" \"$args\""
	  helper_cmd="google-chrome --aggressive-cache-discard --disable-notifications --enable-aggressive-domstorage-flushing --disable-client-side-phishing-detection --disable-gpu --restore-last-session --no-first-run --disable-translate --password-store=basic --user-data-dir=\"$izopen_tmp_dir/google-chrome-$tunnel_port_current\" --proxy-server=\"socks5://localhost:$tunnel_port_current\" \"$args\""
	else
	  helper_cmd="midori -c \"$izopen_tmp_dir/midori-$tunnel_port_current\" \"$args\""
	fi
#    else
#	helper_cmd="xdg-open \"$args\""
  fi
}

helper_https() {
	helper_http "$args"
}

helper_about() {
	helper_http "$args"
}

helper_smb() {
  helper_cmd="xdg-open \"$args\""
}

helper_cifs() {
  helper_cmd="xdg-open \"$args\""
}


# SYSTEM FUNCTIONS
# DON'T TOUCH ANYTHING BELLOW
#########################################################################

helper_tunnel_create() {
 # put specific address port forwarding port config file
 izopen_tmp_socks_address="$izopen_tmp_dir/socks_host_$(echo $address | sed -e 's/[^A-Za-z0-9_-]/_/g').conf"

 # don't create a new tunnel if it's already opened
 if [ -f "$izopen_tmp_socks_address" ]
  then
	nc 127.0.0.1 $(cat "$izopen_tmp_socks_address") </dev/null 2>/dev/null
	[ $? != 0 ] && tunnel_create=1 || tunnel_create=0
 fi
 if [ "$tunnel_create" = 1 ]
  then
          # make tmp dir if not exist
          [ ! -e "$izopen_tmp_dir" ] && mkdir -p "$izopen_tmp_dir"

          # import port configuration of remote address if exist
	  if [ -e "$izopen_tmp_socks_address" ] ; then 
		tunnel_port_create="$(cat "$izopen_tmp_socks_address")"
          fi

          if [ ! -e "$izopen_tmp_socks_address" ] ; then
              # find first free port
              local port
              port=$tunnel_port_min

              until [ ! -z "$tunnel_port_create" ]; do
                izopen_tmp_socks_proxy="$izopen_tmp_dir/proxychains.$port.conf"
                if [ ! -e "$izopen_tmp_socks_proxy" ];then 
                    tunnel_port_create=$port 
                    echo -e "strict_chain\nquiet_mode\nproxy_dns\n[ProxyList]\nsocks5  127.0.0.1 $port" > "$izopen_tmp_socks_proxy"
                  else
                    let port++
                fi
              done
          fi

	  # save the current address used port
	  echo $tunnel_port_create > "$izopen_tmp_socks_address"

	  # save the last used/reused port
	  echo $tunnel_port_create > "$izopen_tmp_socks_port_current"

	  # dynamic port forwarding with compression
	  # add ssh options to create socks tunnel and compression
	  helper_cmd_opts+="-D $tunnel_port_create "
 fi
}

helper_tunnel() {
 # create the ssh tunnel if the url is ssh://
 case ${schema} in
   ssh)
       # don't use tunnel if the schema is ssh and is not forced
       [ "$tunnel_use_force_ssh" = 0 ] && tunnel_use=0
       helper_tunnel_create
       ;;
 esac

 # ask for a port if we want use a tunnel
 if [ $tunnel_use = 1 ] ; then
   #tunnel_port_current=$(yad --title "izOpen SSH Proxy" --entry --entry-text=$tunnel_port_current --text="Inserire la porta del Proxy Socks \nCompresa fra $tunnel_port_min e $tunnel_port_max\n" 2>/dev/null)

   tunnel_port_current=$(yad --center --title "izOpen SSH Proxy" --entry --numeric --entry-text=$tunnel_port_current --text="<b>Inserire la porta del Proxy Socks</b> \nCompresa fra $tunnel_port_min e $tunnel_port_max\n" $tunnel_port_min $tunnel_port_max --timeout=10 --timeout-indicator=bottom | tr -d [:alpha:] | tr -d [:cntrl:] | tr -d [:space:])

   # save the current used port for later usage
   [ ! -z "$tunnel_port_current" ] && echo $tunnel_port_current > "$izopen_tmp_socks_port_current"
 fi

 # debug
 #echo tunnel_create=$tunnel_create
 #echo tunnel_use=$tunnel_use
 #echo tunnel_port_current="$tunnel_port_current"

 # create the proxychains4 config
 if [[ $tunnel_use = 1 && ! -z $tunnel_port_current && $tunnel_port_current =~ ^-?[0-9]+$ && $tunnel_port_current -ge $tunnel_port_min && $tunnel_port_current -le $tunnel_port_max ]]
  then
        # proxychains configuration
        helper_cmd_prepend="proxychains4 -f $izopen_tmp_dir/proxychains.$tunnel_port_current.conf "
#  else
#    [ ! -z $tunnel_port_current ] && yad --center --error --text="La porta specificata non è valida: $tunnel_port_current\n\nInserire una porta compresa fra $tunnel_port_min e $tunnel_port_max" 2>/dev/null && unset tunnel_port_current
 fi

 # don't use tunnel socks proxy if the port is not specified or wrong
 [ -z $tunnel_port_current ] && tunnel_use=0
}

print_debug() {
	# print the parsed fields
	echo "========================================================================================"
	echo "$(date +"%Y-%m-%d %H:%M:%S %Z") [debug]: $0 $args"
	echo "----------------------------------------------------------------------------------------"
	echo "       uri: $uri"
	echo "    schema: $schema"
	echo "  username: $username"
	echo "  password: $password"
	echo "   address: $address"
	echo "      port: $port"
	echo "      path: $path"
	echo "   uri tmp: $uritmp"
	echo "helper cmd: $helper_cmd"
	echo "--- output:"
}

open_uri() {
  local uri="$1"
  local args="$@"
  shift
  local opts="$@"
  uri_parser "$uri"

  # workarounds
  [ "${schema}" = "sftp" ] && schema="ssh" # force ssh with sftp url

  ##
  ## customize the following uri for command associations:
  ##
  case ${schema} in
        ssh|telnet|rdp|vnc|sftp|ftp|http|https|about|smb|cifs|file)
		# create or use ssh tunnel if required
		[[ "$tunnel_create" = 1 || "$tunnel_use" = 1 ]] && helper_tunnel "$args"
		# obtain commands to use to connect
		helper_${schema} "$args"
		# because google chrome doesn't works with proxychains, I don't use it
		if [[ "$schema" = "http" && $helper_http_chrome = 1 ]]; then
		  helper_cmd="$helper_cmd"
		else
		  helper_cmd="${helper_cmd_prepend}${helper_cmd}"
		fi

		[ $debug = 1 ] && print_debug

		# connect to remote server
		eval "$helper_cmd"
                [ $? != 0 ] && tail -n 30 /tmp/izopen.log | sed -n 'H; /^=/h; ${g;p;}' | yad --center --width=900 --height=500 --title "Connection Error" --button=gtk-close:0 --text "Errors from /tmp/izopen.log" --text-info | grep -v "WINDOW DECORATIONS RELOADED"
		;;
        *)
		echo "ERROR: invalid URI specified: $args"
		;;
  esac
}


#
# URI parsing function
#
# The function creates global variables with the parsed results.
# It returns 0 if parsing was successful or non-zero otherwise.
#
# [schema://][user[:password]@]address[:port][/path][?[arg1=val1]...][#fragment]
#
# from http://vpalos.com/537/uri-parsing-using-bash-built-in-features/
#
function uri_parser2() {
    # uri capture
    uri="$@"

    # safe escaping
    uri="${uri//\`/%60}"
    uri="${uri//\"/%22}"

    # top level parsing
    pattern='^(([a-z]{3,5})://)?((([^:\/]+)(:([^@\/]*))?@)?([^:\/?]*)(:([0-9]+))?)(\/[^?]*)?(\?[^#]*)?(#.*)?$'
    [[ "$uri" =~ $pattern ]] || return 1;

    # component extraction
    uri=${BASH_REMATCH[0]}
    schema=${BASH_REMATCH[2]}
    address=${BASH_REMATCH[3]}
    username=${BASH_REMATCH[5]}
    password=${BASH_REMATCH[7]}
    address=${BASH_REMATCH[8]}
    port=${BASH_REMATCH[10]}
    path=${BASH_REMATCH[11]}
    query=${BASH_REMATCH[12]}
    fragment=${BASH_REMATCH[13]}

    # path parsing
    count=0
    path="$uri_path"
    pattern='^/+([^/]+)'
    while [[ $path =~ $pattern ]]; do
        eval "uri_parts[$count]=\"${BASH_REMATCH[1]}\""
        path="${path:${#BASH_REMATCH[0]}}"
        let count++
    done

    # query parsing
    count=0
    query="$uri_query"
    pattern='^[?&]+([^= ]+)(=([^&]*))?'
    while [[ $query =~ $pattern ]]; do
        eval "uri_args[$count]=\"${BASH_REMATCH[1]}\""
        eval "uri_arg_${BASH_REMATCH[1]}=\"${BASH_REMATCH[3]}\""
        query="${query:${#BASH_REMATCH[0]}}"
        let count++
    done

    # return success
    return 0
}


#      desc: set/check/sanitize/validate a URI and the gained variables
#      args: $1
# args desc: 'URI'
#    return: misc variables containing the URI data
uri_parser() {
    # uri capture
    uri="$@"

    # safe escaping
    uri="${uri//\`/%60}"
    uri="${uri//\"/%22}"

    local query1 query2 path1 path2

    # extract the schema
    protourl="$(echo $uri | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    schema="$(echo $protourl | cut -d":" -f1 )"

    if [[ ! -z $schema ]] ; then
            # remove the schema
            url="$(echo ${1/$protourl/})"

            # since kde plasma 5.16 there is a bug when specifing extra port that add ?line=PORT&column=0
            url="$(echo $url | sed 's/?line=/:/' | sed 's/&column=0//')"

            # extract the user (if any)
            login="$(echo $url | grep @ | cut -d@ -f1)"
            username="$(echo $login | cut -d: -f1)"
            password="$(echo $login | grep : | cut -d: -f2)"
	    password="$(echo "$password" | sed 's/!/\\!/g' | sed 's/'\''/\\'\''/g')"

            # extract the address
            port="$(echo ${url/"$login"@/} | cut -d/ -f1)"
            address="$(echo ${port} | cut -d: -f1)"

            # by request - try to extract the port
            port="$(echo $port | grep ":" | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"

            # extract the uri (if any)
            resource="/$(echo $url | grep / | cut -d/ -f2-)"
    else
            url=""
            login=""
            username=""
            password=""
            address=""
            port=""
            resource=$1
    fi

    # extract the path (if any)
    path1="$(echo $resource | grep ? | cut -d? -f1 )"
    path2="$(echo $resource | grep \# | cut -d# -f1 )"
    path=$path1
    if [[ -z $path ]] ; then path=$path2 ; fi
    if [[ -z $path ]] ; then path=$resource ; fi

    # extract the query (if any)
    query1="$(echo $resource | grep ? | cut -d? -f2-)"
    query2="$(echo $query1 | grep \# | cut -d\# -f1 )"
    query=$query2
    if [[ -z $query ]] ; then query=$query1 ; fi

    # extract the fragment (if any)
    fragment="$(echo $resource | grep \# | cut -d\# -f2 )"

    url="$protourl$url"

    if [ $debug = 2 ]; then
     echo "url: $url"
     echo "  schema: $schema"
     echo "   login: $login"
     echo "username: $username"
     echo "password: $password"
     echo " address: $address"
     echo "    port: $port"
     echo "resource: $resource"
     echo "    path: $path"
     echo "   query: $query"
     echo "fragment: $fragment"
     echo ""
    fi
}


case $1 in 
  switch)
	[ -f "/tmp/izopen.conf" ] && . /tmp/izopen.conf
	[ "$tunnel_use_force_ssh" = "0" ] && echo "tunnel_use_force_ssh=1" > /tmp/izopen.conf || echo "tunnel_use_force_ssh=0" > /tmp/izopen.conf
	;;
  tunnel)
	shift
	tunnel_create=1
	tunnel_use=1
	open_uri "$@"
	;;
  clean)
	#rm -f "$izopen_tmp_dir"/*.conf
	;;

       *)
	[ $tunnel_create_force = 1 ] && tunnel_create=1
	[ $tunnel_use_force = 1 ] && tunnel_use=1
	open_uri "$@" 2>&1 | tee -a /tmp/izopen.log 2>&1
	;;
esac

